var mycanvas = document.getElementById('mycanvas');
var ctx = mycanvas.getContext('2d');
var snakeSize = 20;
var w = 700;
var h = 700;
var score = 0;
var highScore = localStorage.getItem("highScore") || 0;
var snake;
var snakeSize = 20;
var food;
