var tracks = [
	{
		id: 0,
		name: "Test1",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 4 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 4 },
		]
	},
	{
		id: 1,
		name: "Test2",
		baskets: [
			{ nr: 1, par: 5 },
			{ nr: 2, par: 5 },
			{ nr: 3, par: 6 },
			{ nr: 4, par: 6 },
			{ nr: 5, par: 6 },
		]
	},
	{
		id: 2,
		name: "Test3",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 4 },
			{ nr: 5, par: 3 },
		]
	},
	{
		id: 3,
		name: "Jõulumäe Kollane",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 5 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
			{ nr: 11, par: 3 },
			{ nr: 12, par: 5 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 4 },
			{ nr: 18, par: 3 },
			{ nr: 19, par: 3 },
			{ nr: 20, par: 3 },
			{ nr: 21, par: 3 },
			{ nr: 22, par: 3 },
			{ nr: 23, par: 3 },
			{ nr: 24, par: 3 },
			{ nr: 25, par: 3 },
			{ nr: 26, par: 3 },
			{ nr: 27, par: 3 },
		]
	},
	{
		id: 4,
		name: "Jõulumäe Punane",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 4 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 4 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 4 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 4 },
			{ nr: 11, par: 3 },
			{ nr: 12, par: 4 },
			{ nr: 13, par: 4 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 4 },
			{ nr: 18, par: 4 },
		]
	},
	{
		id: 5,
		name: "Keila harrastajate rada",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
			{ nr: 11, par: 4 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 3 },
			{ nr: 19, par: 3 },
			{ nr: 20, par: 3 },
			{ nr: 21, par: 3 },
			{ nr: 22, par: 3 },
			{ nr: 23, par: 3 },
			{ nr: 24, par: 3 },
		]
	},
	{
		id: 6,
		name: "Keila võistlusrada",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 4 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 5 },
			{ nr: 8, par: 4 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 4 },
			{ nr: 11, par: 4 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 4 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 3 },
		]
	},
	{
		id: 7,
		name: "Kiiu",
		baskets: [
			{ nr: 1, par: 4 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
		]
	},
	{
		id: 8,
		name: "Kilingi-Nõmme",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
		]
	},
	{
		id: 9,
		name: "Maarjamäe",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
		]
	},
	{
		id: 10,
		name: "Männiku",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
			{ nr: 11, par: 3 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 4 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 3 },
		]
	},
	{
		id: 11,
		name: "Nõmme 2016",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 4 },
			{ nr: 11, par: 3 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 4 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 4 },
			{ nr: 19, par: 3 },
		]
	},
	{
		id: 12,
		name: "Otepää suverada",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 4 },
			{ nr: 11, par: 3 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 3 },
		]
	},
	{
		id: 13,
		name: "Pärnu Jõekääru",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 4 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 4 },
			{ nr: 11, par: 4 },
			{ nr: 12, par: 3 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 4 },
			{ nr: 17, par: 3 },
			{ nr: 18, par: 3 },
		]
	},
	{
		id: 14,
		name: "Pärnu Rääma",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 3 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 3 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 3 },
			{ nr: 9, par: 3 },
		]
	},
	{
		id: 15,
		name: "Valgehobusemäe",
		baskets: [
			{ nr: 1, par: 3 },
			{ nr: 2, par: 4 },
			{ nr: 3, par: 3 },
			{ nr: 4, par: 3 },
			{ nr: 5, par: 4 },
			{ nr: 6, par: 3 },
			{ nr: 7, par: 3 },
			{ nr: 8, par: 4 },
			{ nr: 9, par: 3 },
			{ nr: 10, par: 3 },
			{ nr: 11, par: 4 },
			{ nr: 12, par: 4 },
			{ nr: 13, par: 3 },
			{ nr: 14, par: 3 },
			{ nr: 15, par: 3 },
			{ nr: 16, par: 3 },
			{ nr: 17, par: 4 },
			{ nr: 18, par: 3 },
			{ nr: 19, par: 3 },
			{ nr: 20, par: 3 },
			{ nr: 21, par: 4 },
		]
	},

];
